const KEY="taskapp.trello-mockup.v2",rank={high:0,medium:1,low:2,unset:3};
const mk=(id,title,priority="unset")=>({id,title,priority,dueAt:null,description:"",createdAt:new Date().toISOString(),comments:[]});
const initial=()=>({title:"タスクボード",lists:[{id:"todo",title:"未着手",sortMode:"manual",cards:[mk("c1","要件を確認する","high"),mk("c2","画面を作る","medium")]},{id:"doing",title:"進行中",sortMode:"manual",cards:[mk("c3","ドラッグ&ドロップを実装する","low")]},{id:"done",title:"完了",sortMode:"manual",cards:[mk("c4","プロトタイプを作成する")]}]});
const id=p=>`${p}-${crypto.randomUUID?.()||Date.now()}`,escape=s=>{const e=document.createElement("div");e.textContent=s;return e.innerHTML},listsEl=document.querySelector("#lists"),status=document.querySelector("#status"),detail=document.querySelector("#detail"),confirm=document.querySelector("#confirm");let dragging,pending;
function normalize(c){return{...c,priority:rank[c.priority]===undefined?"unset":c.priority,dueAt:c.dueAt||null,description:c.description||"",createdAt:c.createdAt||new Date().toISOString(),comments:Array.isArray(c.comments)?c.comments:[]}}
function load(){try{let b=JSON.parse(localStorage.getItem(KEY));if(b?.lists){b.lists=b.lists.map(l=>({...l,sortMode:["manual","priority","dueAt","createdAt"].includes(l.sortMode)?l.sortMode:"manual",cards:l.cards.map(normalize)}));return b}}catch{}return initial()}let board=load();
const list=id=>board.lists.find(x=>x.id===id),card=(l,id)=>list(l).cards.find(x=>x.id===id),say=(m,e=false)=>{status.textContent=m;status.classList.toggle("error",e)},save=()=>{try{localStorage.setItem(KEY,JSON.stringify(board));return true}catch{say("保存できませんでした。",true);return false}},date=x=>new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(x));
function sort(l){if(l.sortMode==="priority")l.cards.sort((a,b)=>rank[a.priority]-rank[b.priority]);if(l.sortMode==="dueAt")l.cards.sort((a,b)=>(a.dueAt?+new Date(a.dueAt):Infinity)-(b.dueAt?+new Date(b.dueAt):Infinity));if(l.sortMode==="createdAt")l.cards.sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt))}function commit(m){save();render();say(m)}
function menu(type,l,c=" "){return `<details class="menu"><summary>•••</summary><div class="popup"><button data-a="edit-${type}" data-l="${l}" data-c="${c}">編集</button>${type==="card"?`<button data-a="move" data-l="${l}" data-c="${c}">移動…</button>`:""}<button data-a="delete-${type}" data-l="${l}" data-c="${c}">削除</button></div></details>`}function cardView(l,c){let p=c.priority!=="unset"?`<span class="badge ${c.priority}">${({high:"高",medium:"中",low:"低"})[c.priority]}</span>`:"",d=c.dueAt?`<span>◷ ${date(c.dueAt)}</span>`:"";return `<article class="card" draggable="true" tabindex="0" data-l="${l.id}" data-c="${c.id}"><div>${escape(c.title)}</div>${p||d?`<div class="meta">${p}${d}</div>`:""}<span class="card-menu">${menu("card",l.id,c.id)}</span></article>`}function listView(l){return `<article class="list"><header class="list-head"><h2>${escape(l.title)}</h2><select class="sort" data-a="sort" data-l="${l.id}"><option value="manual" ${l.sortMode==="manual"?"selected":""}>手動順</option><option value="priority" ${l.sortMode==="priority"?"selected":""}>優先度順</option><option value="dueAt" ${l.sortMode==="dueAt"?"selected":""}>期限順</option><option value="createdAt" ${l.sortMode==="createdAt"?"selected":""}>作成日時順</option></select>${menu("list",l.id)}</header><div class="cards" data-drop="${l.id}">${l.cards.map(c=>cardView(l,c)).join("")}</div><div data-add="${l.id}"><button class="add" data-a="add-card" data-l="${l.id}">＋ カードを追加</button></div></article>`}function render(){document.querySelector("#title").textContent=board.title;listsEl.innerHTML=board.lists.map(listView).join("")+`<section class="add-list"><button data-a="add-list">＋ 別のリストを追加</button></section>`}
function form(type,l=""){return `<form class="add-form" data-form="${type}" data-l="${l}"><input name="title" placeholder="${type==="list"?"リスト名":"カード名"}"><p class="error"></p><button class="primary">追加</button><button data-a="close" type="button">×</button></form>`}function openForm(type,l){let h=type==="list"?listsEl.lastElementChild:document.querySelector(`[data-add="${l}"]`);h.innerHTML=form(type,l);h.querySelector("input").focus()}
function comments(c){document.querySelector("#comment-list").innerHTML=c.comments.length?c.comments.map(x=>`<article class="comment"><p>${escape(x.text)}</p><time>${date(x.createdAt)}</time></article>`).join(""):'<p>まだコメントはありません。</p>'}function openDetail(l,c){let x=card(l,c),f=document.querySelector("#detail-form");f.listId.value=l;f.cardId.value=c;f.title.value=x.title;f.priority.value=x.priority;f.dueAt.value=x.dueAt?x.dueAt.slice(0,16):"";f.description.value=x.description;comments(x);detail.showModal()}
function closeMenus(except){document.querySelectorAll("details[open]").forEach(x=>{if(x!==except)x.removeAttribute("open")})}document.addEventListener("toggle",e=>{if(e.target.matches("details[open]"))closeMenus(e.target)},true);
document.addEventListener("click",e=>{let b=e.target.closest("[data-a]");if(b){e.stopPropagation();let d=b.dataset;if(d.a==="add-card")openForm("card",d.l);if(d.a==="add-list")openForm("list");if(d.a==="close")render();if(d.a==="edit-card")openDetail(d.l,d.c);if(d.a==="edit-list"){let x=list(d.l),v=prompt("リスト名",x.title);if(v?.trim()){x.title=v.trim();commit("リスト名を更新しました。")}}if(d.a==="delete-card"||d.a==="delete-list"){pending={type:d.a.endsWith("list")?"list":"card",l:d.l,c:d.c};let x=pending.type==="list"?list(d.l):card(d.l,d.c);document.querySelector("#confirm-message").textContent=`「${x.title}」を削除します。`;confirm.showModal()}if(d.a==="move"){let n=prompt(board.lists.map((x,i)=>`${i+1}: ${x.title}`).join("\n"));let to=board.lists[+n-1];if(to){let from=list(d.l),i=from.cards.findIndex(x=>x.id===d.c),[x]=from.cards.splice(i,1);to.cards.push(x);sort(to);commit("カードを移動しました。")}}return}let x=e.target.closest(".card");if(x)openDetail(x.dataset.l,x.dataset.c)});
document.addEventListener("change",e=>{if(e.target.dataset.a!=="sort")return;let l=list(e.target.dataset.l);l.sortMode=e.target.value;sort(l);commit("並べ替えを更新しました。")});document.addEventListener("submit",e=>{if(!e.target.matches(".add-form"))return;e.preventDefault();let f=e.target,v=f.elements.title.value.trim();if(!v){f.querySelector(".error").textContent="名前を入力してください。";return}if(f.dataset.form==="list")board.lists.push({id:id("list"),title:v,sortMode:"manual",cards:[]});else{let l=list(f.dataset.l);l.cards.push(mk(id("card"),v));sort(l)}commit("追加しました。")});
document.querySelector("#detail-form").addEventListener("submit",e=>{if(e.submitter?.value!=="save")return;e.preventDefault();let f=e.currentTarget,x=card(f.listId.value,f.cardId.value),v=f.title.value.trim();if(!v)return say("カード名を入力してください。",true);x.title=v;x.priority=f.priority.value;x.dueAt=f.dueAt.value?new Date(f.dueAt.value).toISOString():null;x.description=f.description.value.trim();sort(list(f.listId.value));save();detail.close();commit("カード詳細を保存しました。")});document.querySelector("#comment-form").addEventListener("submit",e=>{e.preventDefault();let f=e.currentTarget,d=document.querySelector("#detail-form"),v=f.elements.text.value.trim();if(!v){f.querySelector(".error").textContent="コメントを入力してください。";return}let x=card(d.listId.value,d.cardId.value);x.comments.push({id:id("comment"),text:v,createdAt:new Date().toISOString()});f.reset();save();comments(x);say("コメントを追加しました。")});
document.addEventListener("dragstart",e=>{let x=e.target.closest(".card");if(!x)return;dragging={l:x.dataset.l,c:x.dataset.c};x.classList.add("drag")});document.addEventListener("dragend",e=>{e.target.closest(".card")?.classList.remove("drag");document.querySelectorAll(".cards").forEach(x=>x.classList.remove("drop"));dragging=null});document.addEventListener("dragover",e=>{let x=e.target.closest(".cards");if(x&&dragging){e.preventDefault();x.classList.add("drop")}});document.addEventListener("drop",e=>{let area=e.target.closest(".cards");if(!area||!dragging)return;e.preventDefault();let from=list(dragging.l),i=from.cards.findIndex(x=>x.id===dragging.c),[x]=from.cards.splice(i,1),to=list(area.dataset.drop);to.cards.push(x);from.sortMode=to.sortMode="manual";commit("カードを移動しました。")});confirm.addEventListener("close",()=>{if(confirm.returnValue!=="confirm"||!pending)return;if(pending.type==="list")board.lists=board.lists.filter(x=>x.id!==pending.l);else list(pending.l).cards=list(pending.l).cards.filter(x=>x.id!==pending.c);commit("削除しました。")});render();
